### ISSUE TITLE
貌似ios11以下横屏显示按钮会全部消失

### ISSUE THREAD

**Issue by Whyjsee** [ghostlordstar/GLKLineKit#1]
貌似ios11以下横屏显示按钮会全部消失掉，ios11的话才能正常显示

**Comment by ghostlordstar** [comment]
哎，最近很忙，这个库一直没时间更新，等闲了再好好搞一下。
你的问题我也遇到了，应该是autoLayout的问题，布局时不要用masonry，直接用frame布局就可以了

**Comment by Whyjsee** [comment]
谢谢回复@ghostlordstar

**Comment by Whyjsee** [comment]
@ghostlordstar  p_transFormBackView中旋转改成self.view.transform = CGAffineTransformMakeRotation(M_PI_2); 就能适配11以下的了

**Comment by ghostlordstar** [comment]
这样就可以么？😲 要不要其他设置？

**Comment by Whyjsee** [comment]
@ghostlordstar  不用的，仅仅改成这一句话就ok了，亲测可行，应该是因为以前旋转用的GetCGAffineTransformRotateAroundPoint中设置了旋转中心点这东东和masonry的约束起冲突了，应该是这样👍

**Comment by Whyjsee** [comment]
@ghostlordstar 这个轮子造的挺不错的，性能的确很强大👍
