### ISSUE TITLE
楼主可以给个联系方式吗~~~

### ISSUE THREAD

**Issue by LiuYongJ** [ghostlordstar/GLKLineKit#2]
楼主可以建个群一起交流吗~~小白一枚，求大神指导一下~~~~

**Comment by ghostlordstar** [comment]
有这个想法，但是最近有点忙。等忙过这段时间吧，等开群时私信你

**Comment by lgl2444** [comment]
楼主可以给个qq号吗,在加入cell中,无法缩放,怎么解决

**Comment by ghostlordstar** [comment]
@lgl2444 是因为手势冲突的问题，缩放时需要禁用scrollview父视图的滑动手势
