### ISSUE TITLE
楼主，对于 不同时间的 k线图 

### ISSUE THREAD

**Issue by TomJack1** [ghostlordstar/GLKLineKit#4]
不同时间的 的k线图 有问题

**Comment by ghostlordstar** [comment]
不同时间，指什么？你是说有休市的情况么？

**Comment by TomJack1** [comment]
没问题了。 在问楼主一下。设置了 最大显示蜡烛数量。滑动到头部的时候出现一大段空白，不是从x = 0 开始绘图。

**Comment by ghostlordstar** [comment]
对，那个是故意设置的，为了十字线能看到最边上的一条K线，可以用属性控制：
```
// KLineViewConfig类
/**
 最小显示k线数量
 */
- (NSInteger)minShowKlineCount;
```

**Comment by TomJack1** [comment]
感谢谢楼主的 回复。 我已经 把你的 深度优化了，基本能满足我的需求。有一点就是你手势控制的 不是太友好。 特别是 在 双指操作上。 我改成了 双指手势 和长按手势这样灵敏多了。移动的没有变。

**Comment by ghostlordstar** [comment]
可以把你的优化部分提交上来，我借鉴一下。原来的手势确实处理的很粗糙

**Comment by TomJack1** [comment]
最近事情比较多，有空的时候提交上来
