### ISSUE TITLE
缩放比例调整成为0.01的时候性能下降的很厉害,如果用CAShapeLayer是否会进一步提升性能

### ISSUE THREAD

**Issue by 249109296** [ghostlordstar/GLKLineKit#5]

**Comment by ghostlordstar** [comment]
有没有测过性能瓶颈在哪块？

**Comment by 249109296** [comment]
测试的时候,发现卡顿的时候,cpu占用特别高.如果换成GPU渲染可能会解决

**Comment by ghostlordstar** [comment]
0.01的比例太小了，计算会消耗大量性能，改成Layer也一样，想提升性能只能在算法上下功夫了。
这个库已经做了一部分性能优化，包括局部计算和数据缓存等方案。如果有更好的方案欢迎提pull requests。

**Comment by 249109296** [comment]
在KLineView加入self.layer.drawsAsynchronously = true; 性能会好一些

**Comment by Whyjsee** [comment]
> 在KLineView加入self.layer.drawsAsynchronously = true; 性能会好一些

换成cashapelayer会快很多，k线图还没测试过，但分时和柱状图替换后是真的快了不少，像你说的0.01比例速度差距很大。

**Comment by ghostlordstar** [comment]
已添加
